spring:
  application:
    name: forumhub
  datasource:
    url: jdbc:postgresql://localhost:5432/DB-forumHub
    username: Bruno
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format-sql: true
