spring:
  application:
    name: forumhub
  datasource:
    url: jdbc:postgresql://localhost:5432/DB-forumHub
    username: Bruno
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    context-path: /api
  error:
    include-stacktrace: never

api:
  security:
    secret: ${JWT_SECRET:secret}
