create table topicos (
    id bigint generated by default as identity,
    titulo varchar(255) not null, 
    mensagem text not null, 
    status varchar(255) check (status in ('ABERTA','RESPONDIDA')) not null, 
    curso_id bigint, 
    data_criacao timestamp(6), 
    autor_id varchar(255),
    primary key (id)
);