create table cursos (
    id bigint generated by default as identity, 
    categoria varchar(255) check (categoria in ('BACKEND','FRONTEND','INFRA','SEGURANCA','MOBILE')) not null,
    nome varchar(255) not null, 
    primary key (id));